function mmse = MMSE(x_data, noise_var, x_min, x_max)
%MMSE Summary of this function goes here
top = integral( ...
    @(x) x .* normal_conditional_pdf(x, x_data, noise_var), ...
    x_min, ...
    x_max ...
);
bottom = integral( ...
    @(x) normal_conditional_pdf(x, x_data, noise_var), ...
    x_min, ...
    x_max ...
);
mmse = top / bottom;
end

